
<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Actividad 1: librería NumPy y Pandas.</font>
___




Ahora que hemos hecho el repaso de la líbreria de NumPy, es momento de probar los conocimientos adquiridos. 

<div class="alert alert-danger" style="margin: 10px"><strong>NOTA IMPORTANTE!</strong> Asegúrese de no escribir código en las celdas donde se muestra ejemplificada la salida (etiquetada como "no escribir aquí") <br> de lo contrario, terminará reescribiendo la salida esperada.</div>

#### 1. importar NumPy como np

In [1]:
# CÓDIGO AQUÍ
import numpy as np

#### 2. Crear un arreglo de ceros de tamaño 10 

In [2]:
arreglo=np.zeros(10)
print(arreglo)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# NO ESCRIBIR AQUÍ

#### 3. Crear un arreglo de unos de tamaño 10 

In [4]:
arreglo=np.ones(10)
print(arreglo)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# NO ESCRIBIR AQUÍ

#### 4. Crear un arreglo de cincos de tamaño 10 

In [6]:
arreglo = np.full(10, 5.0)
print(arreglo)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [7]:
# NO ESCRIBIR AQUÍ

#### 5. Crear un arreglo de enteros que contenga elementos del 10 al 50

In [8]:
arreglo = np.arange(10, 51)

print(arreglo)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [9]:
# NO ESCRIBIR AQUÍ

#### 6. Crear un arreglo de todos los enteros pares en el intervalo de 10 a 50

In [10]:
arreglo = np.arange(10, 51, 2)

print(arreglo)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [11]:
# NO ESCRIBIR AQUÍ

#### 7. Crear una matriz de 3x3 con valores en el rango de 0 a 8.

In [12]:
matriz = np.arange(9).reshape(3, 3)

print(matriz)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# NO ESCRIBIR AQUÍ

#### 8. Crear una matriz identidad de 3x3

In [14]:
identidad = np.eye(3)

print(identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# NO ESCRIBIR AQUÍ

#### 9. Usa NumPy para generar un número aleatorio entre 0 y 1 <br><br>&emsp;NOTA: Tu resultado puede ser diferente al que se muestra en el resultado de ejemplo.

In [16]:

numero = np.random.rand()

print(numero)

0.16394489693999525


In [17]:
# NO ESCRIBIR AQUÍ

#### 10. Usa NumPy para generar un arreglo que contenga 25 números aleatorios muestreados a partir de una distribución normal estándar.<br><br>&emsp;&ensp;NOTA: Los valores de su resultado pueden ser diferentes de los que se muestran en el resultado de ejemplo.

In [18]:

arreglo = np.random.randn(25)

print(arreglo)

[ 1.82396562 -0.90550038 -0.33402685  0.93581062  0.36847511 -0.86851502
  0.78069978  0.93357033 -0.69415736 -0.43749338 -0.48742028  0.90604819
 -0.91224214  0.05173703 -1.14588035 -0.1052556  -0.89610973 -0.38321929
 -0.04115394  2.34222813  0.3991843  -1.18088192 -0.19463117  0.2083719
  0.73982979]


In [19]:
# NO ESCRIBIR AQUÍ

#### 11. Crea la matriz que se muestra en la salida de ejemplo:

In [20]:
# CÓDIGO AQUÍ


In [21]:
# NO ESCRIBIR AQUÍ

#### 12. Crea una matriz de tamaño 20 linealmente espaciada en el intervalo de 0 a 1:

In [22]:
arreglo = np.linspace(0, 1, 20)

print(arreglo)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [23]:
# NO ESCRIBIR AQUÍ

## Indexación y Selección en Numpy 

Ahora se le dará una matriz inicial (¡asegúrese de ejecutar la celda a continuación!) Y se le pedirá que replique las salidas de la matriz que se muestra en la salida de ejemplo:


In [24]:
# EJECUTAR ESTA CELDA. ES NUESTRA MATRIZ DE INICIO
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Escriba código que reproduzca el resultado que se muestra a continuación.<br><br>&emsp;&ensp;Tenga cuidado de no ejecutar la celda inmediatamente arriba de la salida (etiquetada como: "NO ESCRIBIR AQUI"), de lo contrario no podrá ver el resultado de la salida.

In [25]:
# CÓDIGO AQUÍ
mat2 = mat[2:,1:]
print(mat2)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


#### 14. Utilizando el resultado anterior escriba código que reproduzca el resultado que se muestra a continuación.

In [26]:
print(mat2[1, 3])

20


#### 15. Utilizando el resultado de Out[14] Escriba código que reproduzca el resultado que se muestra a continuación.

In [27]:
# CÓDIGO AQUÍ
mat3 = mat2[:,0] -10
mat = mat3.reshape(3,1)
print(mat3)

[ 2  7 12]


#### 16. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [28]:
mat = np.arange(1,26).reshape(5,5)
r=mat[4,:]
print(r)

[21 22 23 24 25]


In [29]:
# NO ESCRIBIR AQUÍ

#### 17. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [30]:
re=mat[3:,:]
print(re)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [31]:
# NO ESCRIBIR AQUÍ

## Operaciones con NumPy

#### 18. Obtenga la suma de todos los valores en mat

In [32]:
suma_total = np.sum(mat)

print(suma_total)


325


In [33]:
# NO ESCRIBIR AQUÍ

#### 19. Obtenga la desviación estándar de todos los valores en mat.

In [34]:
desviacion = np.std(mat)
print(desviacion)

7.211102550927978


In [35]:
# NO ESCRIBIR AQUÍ

#### 20. Obtenga la suma de todas las columnas en mat

In [36]:
suma_columnas = np.sum(mat, axis=0)
print(suma_columnas)


[55 60 65 70 75]


In [37]:
# NO ESCRIBIR AQUÍ

## Operaciones con Pandas

**21. importar la librería de pandas**

In [38]:
import pandas as pd
import numpy as np

**22. Lea el archivo bank.csv que se encuentra en la carpeta raíz. ¡Presta mucha atención a la ubicación del archivo .csv!.**

In [39]:
df=r"bank.csv"
bank=pd.read_csv(df)
print(bank)


      age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous 

**23. Mustre las primero 5 filas del dataset**

In [40]:
print(bank.head(5))
      

   age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no  


**24. Calcule el promedio de la edad de las personas del dataset**

In [41]:
promedio_edad = bank['age'].mean()

print("El promedio de edad es:", promedio_edad)

El promedio de edad es: 41.17009511170095


**25. ¿Cuál es el status marital de la persona más joven en el dataset?**



In [42]:
perj=bank['age'].min()
p = bank[bank['age'] == perj]
status_marital = p['marital'].values[0]
print("El status marital de la persona más joven es:", status_marital)

El status marital de la persona más joven es: single


**26. ¿Cuántas categorías de trabajos únicos existen en el dataset?**

In [43]:
num_trabajos = bank['job'].nunique()

print("Existen", num_trabajos, "categorías de trabajos únicas en el dataset")

Existen 12 categorías de trabajos únicas en el dataset


**27. Muestre cuántas personas hay por categoría de trabajo**

In [44]:
conteo_trabajos = bank['job'].value_counts()

print(conteo_trabajos)

job
management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64


**28. ¿Cuál es el porcentaje de las personas en el dataset que están casadas?**

In [45]:
total=len(bank)
num_casados = (bank['marital'] == 'married').sum()
porcentaje_casados = (num_casados / total) * 100
print(f"El {porcentaje_casados:.2f}% de las personas en el dataset están casadas.")

El 61.87% de las personas en el dataset están casadas.


**29. En el dataset existe una columna etiquetada como: "default". Use el comando .map() para crear una nueva columna llamada "default_code" que contenga el valor 0 si el valor de la columna es "no", o 1 si el valor en la columna esta etiquetada como "si". Muestre los 5 primeros valores de esta nueva columna**


In [46]:
bank["default_code"] = bank["default"].map({"no": 0, "si": 1})
print(bank["default_code"].head())

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: default_code, dtype: float64


**30. Usando el método pandas .apply (), cree una nueva columna llamada "marital_code". Esta columna solo contendrá un código abreviado de la posible primera letra del estado civil. (Por ejemplo, "m" para "casado", "s" para "soltero", etc.**

In [47]:
bank["marital_code"] = bank["marital"].apply(lambda x: x[0].lower())
print(bank[["marital", "marital_code"]].head())

   marital marital_code
0  married            m
1  married            m
2   single            s
3  married            m
4  married            m


**31. ¿Cuál fue el trabajp con duración más larga?**

In [48]:
fila_max = bank.loc[bank['duration'].idxmax()]
print("El trabajo con mayor duración es:", fila_max['job'])
print("Duración máxima:", fila_max['duration'])

El trabajo con mayor duración es: unemployed
Duración máxima: 3025


**32. ¿Cuál es el nivel de educación más común para las personas que están desempleadas?**

In [49]:
desempleados = bank[bank['job'] == 'unemployed']
nivel_comun = desempleados['education'].mode()[0]

print("El nivel de educación más común entre los desempleados es:", nivel_comun)

El nivel de educación más común entre los desempleados es: secondary


**33. ¿Cuál es la edad promedio para estar desempleado?**

In [50]:
desempleados = bank[bank['job'] == 'unemployed']

# Calcular la edad promedio
edad_promedio = desempleados['age'].mean()

print("La edad promedio de las personas desempleadas es:", edad_promedio)

La edad promedio de las personas desempleadas es: 40.90625
